FROM node:20-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine
# remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# copy our nginx config
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# nginx already uses non-root internally (good)
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]