services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    restart: always
    env_file:
      - ./backend/.env.prod
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    restart: always
    ports:
      - "5174:80"
    depends_on:
      - backend
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - db
  redis:
    image: redis:7
    restart: always

volumes:
  postgres_data:
